var annotated_dup =
[
    [ "CommandClose", "class_command_close.html", "class_command_close" ],
    [ "CommandCreate", "class_command_create.html", "class_command_create" ],
    [ "CommandEdit", "class_command_edit.html", "class_command_edit" ],
    [ "CommandExit", "class_command_exit.html", "class_command_exit" ],
    [ "CommandFileOpen", "class_command_file_open.html", "class_command_file_open" ],
    [ "CommandHelp", "class_command_help.html", "class_command_help" ],
    [ "CommandMove", "class_command_move.html", "class_command_move" ],
    [ "CommandPrint", "class_command_print.html", "class_command_print" ],
    [ "CommandRemove", "class_command_remove.html", "class_command_remove" ],
    [ "CommandSave", "class_command_save.html", "class_command_save" ],
    [ "CommandSaveAs", "class_command_save_as.html", "class_command_save_as" ],
    [ "CommandSearch", "class_command_search.html", "class_command_search" ],
    [ "CommandValidate", "class_command_validate.html", "class_command_validate" ],
    [ "ControlVariables", "class_control_variables.html", "class_control_variables" ],
    [ "Exit_Program", "class_exit___program.html", "class_exit___program" ],
    [ "ICommand", "class_i_command.html", "class_i_command" ],
    [ "Interaction", "class_interaction.html", "class_interaction" ],
    [ "InvalidValue", "class_invalid_value.html", "class_invalid_value" ],
    [ "JsonArray", "class_json_array.html", "class_json_array" ],
    [ "JsonBool", "class_json_bool.html", "class_json_bool" ],
    [ "JsonCheck", "class_json_check.html", "class_json_check" ],
    [ "JsonNumber", "class_json_number.html", "class_json_number" ],
    [ "JsonObject", "class_json_object.html", "class_json_object" ],
    [ "JsonString", "class_json_string.html", "class_json_string" ],
    [ "JsonValue", "class_json_value.html", "class_json_value" ],
    [ "NotAKeyWord", "class_not_a_key_word.html", "class_not_a_key_word" ],
    [ "NotAValidCloseArray", "class_not_a_valid_close_array.html", "class_not_a_valid_close_array" ],
    [ "NotAValidOpenArray", "class_not_a_valid_open_array.html", "class_not_a_valid_open_array" ],
    [ "UnknownValue", "class_unknown_value.html", "class_unknown_value" ]
];